language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      php: 7.1
      env: SYMFONY_REQUIRE=3.4.* COMPOSER_FLAGS="--prefer-lowest"
    - stage: test
      php: 7.4
      env: SYMFONY_REQUIRE=4.3.*
    - stage: test
      php: 7.4
      env: SYMFONY_REQUIRE=4.4.*
    - stage: test
      php: 7.4
      env: SYMFONY_REQUIRE=5.0.*

    - stage: deploy
      php: 7.1
      script: skip
      before_deploy: make dist
      env: COMPOSER_FLAGS=""
      deploy:
        provider: releases
        api_key:
          secure: a6UEocTNYy3VDqXvf7aV6eQw7QCW9UmUbjzXCJNbPeLs1kqEPiWSaMDdrPiF31eVgNUj8NpgDhUrbFWEysa5n9CPOu9WPyKMiNcBlMvwtRT5RCUBd11Tk5W8raxBqrYZ+qVh4LaKXqcl9Jt2OxHCYxCxbzjISOq7KaOni+JeL+Enn2mbVkJOCAKhntMry9T9HzAekXukWsMDa37uwtVk/ZSA3UiaUGTSIP9MVEXqPLlbBghtXZX7RDUM5rrYIM1DRyJBdwUQCmitMxysvABh0ZnFtQKV2ePYsadQ7swDkOYutXOnreaZDfJpAjkBJc6I30Fs80cPVQaN8f3h2IbD2g1Kp4wwKR/Ug4kbZ8iFtMGLOwYI1OI/rMoUGXQ7k2sUglrkQl2GfG54r7zw/xXBpQnx3Slo7E0xcUryE2JsmjI7C215nLbmFhskMmjGsdIfc84zfpLaiF1ymMrsodCbGqG4+VC/Ew1MQqGMzTJa1Iqhm0ZGJWvJnGc4JUvPeYGRnpClI9t+q+ZNldWveI6DeYWK5WZYpseX/4RrEl4uZbMAGHnaY2vVDgisQ2OsDjljkEJ9/WDJoOVpVDql8QBnc+HI0xdsG7eU8MLR5k7XOD6A3aAsV88BcY5hSvN+/uObDbC7qnh2hLahp1aRErhQe5N97Yb6aYVIAMTc7hrECO4=
        file: dist/rokka-cli.phar
        skip_cleanup: true
        on:
          tags: true

branches:
  only:
    - master
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+(\.\d+)+$/'

before_install:
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - composer update $COMPOSER_FLAGS --no-interaction
  - vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  - bin/rokka-cli
  - vendor/bin/simple-phpunit
